### ISSUE TITLE
Error message " Object refrence not set to an instance of the object"

### ISSUE THREAD

**Issue by jaaguptors** [ShikenNuggets/ArkhamRouteTracker#24] opened 2021-10-26 09:04 UTC
When i try starting the save I just get that error message, but i checke over 10times that save file path is correct.
Thanks in advance

**Comment by ShikenNuggets** [comment] 2021-11-30 04:49
I see two possibilities here. One is that it was an issue with the 240% route specifically after checking for route updates, in which case this should now be fixed [in the newest release](https://github.com/ShikenNuggets/ArkhamRouteTracker/releases/tag/v1.4). Or, you simply didn't have the route files at all somehow, in which case this is not a bug, although the user experience could probably be improved there.

In any case, closing this since there was no follow-up and it's most likely resolved by downloading the newest version.

**Closed by ShikenNuggets** 2021-11-30 04:49 UTC
Labels: bug
